# Generated by Django 5.2.8 on 2025-11-19 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_commercial', models.CharField(max_length=255)),
                ('nom_scientifique', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('categorie', models.CharField(blank=True, max_length=50, null=True)),
                ('necessite_prescription', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Symptome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_symptome', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('statut_commande', models.CharField(choices=[('EN_ATTENTE', 'En Attente'), ('EN_PREPARATION', 'En Préparation'), ('EN_LIVRAISON', 'En Livraison'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], max_length=20)),
                ('total_montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adresse_livraison', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accounts.client')),
                ('livreur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.livreur')),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accounts.pharmacie')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methode_paiement', models.CharField(max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut_paiement', models.CharField(choices=[('SUCCES', 'Succès'), ('ECHEC', 'Échec'), ('EN_COURS', 'En Cours')], max_length=20)),
                ('reference_transaction', models.CharField(blank=True, max_length=100, null=True)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='commerce.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_maj', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.client')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_url', models.CharField(max_length=255)),
                ('date_telechargement', models.DateTimeField(auto_now_add=True)),
                ('statut_validation', models.CharField(choices=[('EN_ATTENTE', 'En Attente'), ('VALIDEE', 'Validée'), ('REFUSEE', 'Refusée')], max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accounts.client')),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accounts.pharmacie')),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_commandee', models.PositiveIntegerField()),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.commande')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='commerce.medicament')),
            ],
            options={
                'unique_together': {('commande', 'medicament')},
            },
        ),
        migrations.CreateModel(
            name='PanierArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='commerce.medicament')),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.panier')),
            ],
            options={
                'unique_together': {('panier', 'medicament')},
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=0)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='commerce.medicament')),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.pharmacie')),
            ],
            options={
                'unique_together': {('pharmacie', 'medicament')},
            },
        ),
        migrations.CreateModel(
            name='MedicamentSymptome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.medicament')),
                ('symptome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.symptome')),
            ],
            options={
                'unique_together': {('medicament', 'symptome')},
            },
        ),
    ]
