# Generated by Django 5.2.8 on 2025-11-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_medicament_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
